[build]
  publish = "."
  command = "echo 'Building with secure Azure Maps key...'"

[context.production]
  environment = { AZURE_MAPS_KEY = "@azure_maps_key" }

# Add redirects if needed
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
