[build]
  publish = "."
  command = '''
    # Install required tools for substitution
    if ! command -v sed &> /dev/null; then
      echo "Error: sed is required but not installed" >&2
      exit 1
    fi

    # Create backup of original file
    cp index.html index.html.bak

    # Perform environment variable substitution
    if sed -i.bak "s|NETLIFY_AZURE_MAPS_KEY|${AZURE_MAPS_KEY}|g" index.html; then
      echo "Successfully injected Azure Maps key"
      rm index.html.bak
    else
      echo "Error injecting environment variables" >&2
      mv index.html.bak index.html
      exit 1
    fi

    echo "Build completed successfully"
  '''

[context.production.environment]
  AZURE_MAPS_KEY = "@azure_maps_key"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
