[build]
  publish = "."
  command = '''
    echo "Injecting environment variables..."
    sed -i "s/NETLIFY_AZURE_MAPS_KEY/$AZURE_MAPS_KEY/g" index.html
    echo "Build complete"

[context.production]
  environment = { AZURE_MAPS_KEY = "@azure_maps_key" }

# Add redirects if needed
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
